# 1.直接创建向量

In [1]:
import numpy as np

# 创建向量
A = [[1,2,3,4,5]]
B = [[1],[2],[3],[4],[5]]

C = np.array(A)
D = np.array(B)

print("行向量 C: \n",C)
print("列向量 D: \n",D)

print("C 的维度: ",C.ndim)
print("D 的维度: ",D.ndim)

print("C 的形状: ",C.shape)
print("D 的形状: ",D.shape)

print("C 的类型: ",type(C))
print("D 的类型: ",type(D))

行向量 C: 
 [[1 2 3 4 5]]
列向量 D: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
C 的维度:  2
D 的维度:  2
C 的形状:  (1, 5)
D 的形状:  (5, 1)
C 的类型:  <class 'numpy.ndarray'>
D 的类型:  <class 'numpy.ndarray'>


In [4]:
A = [1, 2, 3, 4, 5]
C = np.array(A)
print("C = ", C)
print("C.shape = ", C.shape)
print("C.dtype = ", C.dtype)
print("C 的类型:",type(C))

C =  [1 2 3 4 5]
C.shape =  (5,)
C.dtype =  int32
C 的类型: <class 'numpy.ndarray'>


# 2.随机生成向量

In [5]:
import numpy as np
arr1 = np.random.random((1,3))
arr2 = np.random.random((3,1))
arr3 = np.random.randint(3,30,size=(1,3))
arr4 = np.random.randint(3,30,size=(3,1))

print("创建三维行向量，随机数组成: \n", arr1)
print("创建三维列向量，随机数组成: \n", arr2)
print("创建三维行向量，随机整数数组成: \n", arr3)
print("创建三维列向量，随机整数数组成: \n", arr4)

创建三维行向量，随机数组成: 
 [[0.67443099 0.74280324 0.57564829]]
创建三维列向量，随机数组成: 
 [[0.52518423]
 [0.27906428]
 [0.69623028]]
创建三维行向量，随机整数数组成: 
 [[ 9  9 13]]
创建三维列向量，随机整数数组成: 
 [[ 5]
 [17]
 [ 3]]


In [6]:
# 随机生成1维数组
import numpy as np

# 随机生成1维数组
arr = np.random.rand(5)
print("arr=",arr)

arr= [0.54642035 0.97394855 0.63223805 0.37392695 0.35255658]


# 通过reshape 生成向量

In [7]:
# 通过reshape 生成向量
import numpy as np

A= [1,2,3,4,5,6,7,8,9,10]
B = np.array(A)
C = B.reshape(1,-1)
D = C.reshape(-1,1)
print("1维数组:",B)
print("行向量 C:",C)
print("列向量 D:",D)

1维数组: [ 1  2  3  4  5  6  7  8  9 10]
行向量 C: [[ 1  2  3  4  5  6  7  8  9 10]]
列向量 D: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
