# 1. 直接定义

In [ ]:
# 5.3.3 矩阵的创建
import numpy as np

# 创建矩阵
A = [[1, 2, 3,4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr1 = np.array(A)
print("A=",A)
print("通过array函数创建的矩阵arr1=",arr1)

B = ((1,2,3,4), (5,6,7,8), (9,10,11,12))
arr2 = np.array(B)
print("B=",B)
print("通过array函数创建的矩阵arr2=",arr2)

In [6]:
print("A 的类型", type(A))
print("B 的类型", type(B))
print("arr1 的类型", type(arr1))
print("arr2 的类型", type(arr2))


print("arr1 的形状", arr1.shape)
print("arr2 的形状", arr2.shape)

A 的类型 <class 'list'>
B 的类型 <class 'tuple'>
arr1 的类型 <class 'numpy.ndarray'>
arr2 的类型 <class 'numpy.ndarray'>
arr1 的形状 (3, 4)
arr2 的形状 (3, 4)


# 2. 间接创建

In [10]:
# (1) 随机生成矩阵元素
import numpy as np

# 随机生成 3x4 矩阵
arr1 = np.random.random((3, 4))
print(arr1)

# 随机生成int 型 3x4 矩阵
arr2 = np.random.randint(3,30, size=(3, 4))
print(arr2)



[[0.58369079 0.91998574 0.21025147 0.54647012]
 [0.71212989 0.42880765 0.32409135 0.13261073]
 [0.67821398 0.10030949 0.66655573 0.83080283]]
[[28 15 14 28]
 [18  8 14 12]
 [24 27 10  4]]


In [13]:
# 通过reshape()函数可以将矩阵的维度改变，reshape(m,n)表示将矩阵的行数m和列数n改变为m行n列。
# 例如，将一个1行3列的矩阵reshape成3行1列的矩阵，代码如下：

import numpy as np

a = np.array([[1, 2, 3]])
b = a.reshape(3, 1)
print(b,"\n")


# 也可以将一个3行1列的矩阵reshape成1行3列的矩阵，代码如下：

a = np.array([[1], [2], [3]])
b = a.reshape(1, 3)
print(b,"\n")

A = [1,2,3,4,5,6]
B = np.array(A)
C1 = B.reshape(2,3)
C2 = B.reshape(3,2)
print(C1)
print(C2)    
# 注意reshape的顺序，C1是先reshape成2行3列，再reshape成3行2列，C2是先reshape成3行2列，再reshape成2行3列



[[1]
 [2]
 [3]] 

[[1 2 3]] 

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# 3 矩阵元素的存取操作

In [17]:
import numpy as np
A = [1,2,3,4,5,6]
B = np.array(A)
C1 = B.reshape(2,3)
C2 = B.reshape(3,2)

print("输出C1:", C1)
print("输出C2:", C2)

print("输出C1 的第0行元素:", C1[0])
print("输出C1 的前2行元素:", C1[0:2])
print("输出C2 第0行和第2行的元素:", C2[[0,2]])
print("输出C1 的第1列元素:", C1[:,1])
print("输出C2 的第0行元素:", C2[0])


输出C1: [[1 2 3]
 [4 5 6]]
输出C2: [[1 2]
 [3 4]
 [5 6]]
输出C1 的第0行元素: [1 2 3]
输出C1 的前2行元素: [[1 2 3]
 [4 5 6]]
输出C2 第0行和第2行的元素: [[1 2]
 [5 6]]
输出C1 的第1列元素: [2 5]
输出C2 的第0行元素: [1 2]
