In [1]:
import numpy as np

# 定义矩阵
A = np.array([[3,1,-1, 2], [-5,1, 3,-4], [2,0,1,-1],[1,-5,3,-3]])
# 计算行列式
det = np.linalg.det(A)
print("行列式的值为：", det)

b = np.array([1,2,3,4])

# 求解线性方程组 Ax = b
x = np.linalg.solve(A, b)
print("解的结果为：", x)

行列式的值为： 40.0
解的结果为： [0.625 0.375 2.25  0.5  ]


In [2]:
A_inv = np.linalg.inv(A)
det_A = np.linalg.det(A)
print(A_inv)
print(det_A)
det_A_inv = np.linalg.det(A_inv)
print(det_A_inv)

[[-0.125 -0.125  0.4   -0.05 ]
 [ 0.125  0.125  0.2   -0.15 ]
 [ 1.75   0.75  -1.     0.5  ]
 [ 1.5    0.5   -1.2    0.4  ]]
40.0
0.02499999999999999


In [3]:
C = np.dot(A,A_inv)
print(C)

[[ 1.00000000e+00  2.22044605e-16 -8.88178420e-16 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.22044605e-16  3.88578059e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.44089210e-16  1.00000000e+00]]


In [4]:
C2 = A @ A_inv
print (C2)

[[ 1.00000000e+00  2.22044605e-16 -8.88178420e-16 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.22044605e-16  3.88578059e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.44089210e-16  1.00000000e+00]]


In [5]:
C3 = A * A_inv
print(C3)

[[-0.375 -0.125 -0.4   -0.1  ]
 [-0.625  0.125  0.6    0.6  ]
 [ 3.5    0.    -1.    -0.5  ]
 [ 1.5   -2.5   -3.6   -1.2  ]]


In [6]:
np.linalg.det(C2)

0.9999999999999991

In [7]:
import torch

ModuleNotFoundError: No module named 'torch'