In [1]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(x - y)

tensor([5, 7, 9])
tensor([-3, -3, -3])


In [15]:
#计算梯度

import torch

#定义一个函数
def f1(x1, x2):
    return x1**2 + x2**2

def f2(x1, x2):
    return x1**3 + x2**3


#创建变量
x1 = torch.tensor([2.0, 3.0], requires_grad=True)
x2 = torch.tensor([4.0, 5.0], requires_grad=True)
#计算函数值

y = x1 * x2

print(y)

y.backward()

#打印梯度
print(x1.grad,x2.grad)






tensor([ 8., 15.], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs