# 对亚洲球队进行聚类分析

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('data/football_team_data.csv',index_col='国家')
X = df.values


In [5]:
# 对特征进行归一化
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
print(X)

[[-0.5842676   0.05223517 -0.64677721]
 [-0.97679881 -2.12423024 -1.03291285]
 [-0.9466041  -1.77599577 -1.61211632]
 [-1.76186121 -1.86305439 -0.83984503]
 [-0.76543585 -1.16658546 -0.06757374]
 [-0.04076286  0.05223517 -1.22598067]
 [ 0.26118422  0.05223517  0.51162973]
 [-0.34270994  0.05223517 -0.83984503]
 [-0.13134698  0.05223517 -0.45370938]
 [ 0.89527309  0.05223517  1.28390102]
 [ 0.29137893  0.92282133  1.28390102]
 [-0.16154169  0.92282133  0.31856191]
 [ 0.71410485  0.92282133  0.12549408]
 [ 0.5329366   0.92282133  0.70469755]
 [ 2.16345083  0.92282133  1.28390102]
 [-1.58069297 -0.81835099 -1.80518414]
 [-0.49368348  0.05223517  1.28390102]
 [ 0.77449426  0.92282133 -0.26064156]
 [ 2.042672    0.92282133  0.89776537]
 [ 0.11021068  0.92282133  1.0908332 ]]


In [7]:
# 创建模型
from sklearn.cluster import KMeans
model = KMeans(n_clusters=3, max_iter=1000, random_state=0)
model.fit(X)

df["聚类结果"] = model.labels_
print(df)

        2019国际排名  2018世界杯  2015亚洲杯  聚类结果
国家                                      
中国            73       40        7     2
日本            60       15        5     1
韩国            61       19        2     1
伊朗            34       18        6     1
沙特            67       26       10     1
伊拉克           91       40        4     2
卡塔尔          101       40       13     0
阿联酋           81       40        6     2
乌兹别克斯坦        88       40        8     2
泰国           122       40       17     0
越南           102       50       17     0
阿曼            87       50       12     0
巴林           116       50       11     0
朝鲜           110       50       14     0
印尼           164       50       17     0
澳洲            40       30        1     1
叙利亚           76       40       17     0
约旦           118       50        9     0
科威特          160       50       15     0
巴勒斯坦          96       50       16     0


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
