In [3]:
# 2.1.1 入门
import torch

x = torch.arange(12)
print(x)
print(x.shape)
print(x.dtype)
print(x.size())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.int64
torch.Size([12])


In [4]:
X = x.reshape(3, 4)
print(X)
print(X.shape)
print(X.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
torch.int64


In [5]:
zero = torch.zeros((2, 3, 4))
print(zero)

ones = torch.ones((2, 3, 4))
print(ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [6]:
rand = torch.rand(3, 4)
print(rand)

tensor([[0.4997, 0.4236, 0.2611, 0.6607],
        [0.1673, 0.7044, 0.6949, 0.7340],
        [0.3399, 0.8635, 0.9260, 0.2847]])


In [7]:
arr = torch.tensor([[2,1,4,3], [5, 6, 1, 2], [4, 5, 6,7]])
print(arr)
print(arr.shape)
print(arr.dtype)

tensor([[2, 1, 4, 3],
        [5, 6, 1, 2],
        [4, 5, 6, 7]])
torch.Size([3, 4])
torch.int64


In [15]:
# 2.1.2 运算符
x = torch.tensor([1.0, 2, 4,8])
print(x)
y = torch.tensor([2, 2, 2, 2])
print(y,x + y,x - y,x * y,x / y,x ** y)

tensor([1., 2., 4., 8.])
tensor([2, 2, 2, 2]) tensor([ 3.,  4.,  6., 10.]) tensor([-1.,  0.,  2.,  6.]) tensor([ 2.,  4.,  8., 16.]) tensor([0.5000, 1.0000, 2.0000, 4.0000]) tensor([ 1.,  4., 16., 64.])


In [9]:
print(torch.exp(x))
print(torch.log(x))

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([0.0000, 0.6931, 1.3863, 2.0794])


In [18]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
XY0 = torch.cat((X,Y),dim=0),
XY1 = torch.cat((X,Y),dim=1)
print(XY0)
print(XY1)
print(X == Y)
print(X.sum())

(tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),)
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


In [20]:
# 2.1.3 广播机制
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
print(a,b)

print("a + b", a + b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
a + b tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [23]:
#2.1.4 索引和切片
print("X,Y =",X,Y)
print("X[0],Y[0] =",X[0],Y[0])
print("X[1:3],Y[1:3] =",X[1:3],Y[1:3])
print("X[-1],Y[-1] =",X[-1],Y[-1])
print("X[0:2,:]=",X[0:2,:])


X,Y = tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
X[0],Y[0] = tensor([0., 1., 2., 3.]) tensor([2., 1., 4., 3.])
X[1:3],Y[1:3] = tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])
X[-1],Y[-1] = tensor([ 8.,  9., 10., 11.]) tensor([4., 3., 2., 1.])
X[0:2,:]= tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])


In [25]:
# 2.1.5 节省内存的技巧
before = id(Y)
Y = Y + X
print(id(Y) == before)  # False

Z = torch.zeros_like(Y)
print("id(Z):", id(Z)) 
Z[:] = Y + X
print("id(Z):", id(Z))

before = id(X)
X += Y
print(id(X) == before)  # True

False
id(Z): 1992008248096
id(Z): 1992008248096
True


In [27]:
#2.1.6 转换为其他Python 对象
A = X.numpy()
B = torch.tensor(A)
print(type(A), type(B))

a = torch.tensor([3.5])
print(a,a.item(),float(a),int(a))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([3.5000]) 3.5 3.5 3
