In [1]:
# 2.3.1 标量
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor(5.)
tensor(1.)
tensor(6.)
tensor(1.5000)
tensor(9.)


In [6]:
# 2.3.2 向量
x = torch.arange(4)
print(x) # 输出 [0 1 2 3]
print(x.shape) # 输出 torch.Size([4])
print(x.dtype) # 输出 torch.int64
print(x.device) # 输出 cpu
print(x[3]) # 输出 tensor(3)
print(len(x)) # 输出 4

tensor([0, 1, 2, 3])
torch.Size([4])
torch.int64
cpu
tensor(3)
4


In [ ]:
# 2.3.3 矩阵
A = torch.arange(20).reshape(5, 4)
print(A)

B = torch.tensor([[1, 2,3], [2,0,4],[3,4, 5]])
print(B)
print(B.T)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


In [9]:
# 2.3.4 张量
X = torch.arange(24).reshape(2, 3,4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [11]:
# 2.3.5 张量算法的基本性质
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
print(A)
print(A + B)
print(A * B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [12]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print(a + X)
print((a + X).shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


In [15]:
# 2.3.6 降维
x = torch.arange(4, dtype=torch.float32)
print(x,x.sum())

print("A =",A)
print("A.shape =",A.shape)
print("A.sum() =",A.sum())

tensor([0., 1., 2., 3.]) tensor(6.)
A = tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
A.shape = torch.Size([5, 4])
A.sum() = tensor(190.)


In [18]:
A_sum_axis0 = A.sum( axis=0)
A_sum_axis1 = A.sum( axis=1)
print(A_sum_axis0)
print(A_sum_axis1)
print(A_sum_axis0.shape)
print(A_sum_axis1.shape)

tensor([40., 45., 50., 55.])
tensor([ 6., 22., 38., 54., 70.])
torch.Size([4])
torch.Size([5])


In [21]:
sum_A = A.sum(axis=1,keepdims=True)
print(sum_A)
print(A / sum_A)
print(A.cumsum(axis=0)) # 累积求和

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [22]:
# 2.3.7 点积
y = torch.ones(4, dtype=torch.float32)
print(x,y)
z = torch.dot(x, y)
print(z)

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.])
tensor(6.)


In [25]:
# 2.3.8 矩阵-向量积
print(A.shape,x.shape)
print("A=",A)
print("x=",x)
print("Ax=",torch.mv(A,x))
print("A@x=",A@x)

torch.Size([5, 4]) torch.Size([4])
A= tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
x= tensor([0., 1., 2., 3.])
Ax= tensor([ 14.,  38.,  62.,  86., 110.])
A@x= tensor([ 14.,  38.,  62.,  86., 110.])


In [27]:
# 2.3.9 矩阵乘法
B = torch.ones(4, 3)
print("A = ", A)
print("B = ", B)
print("A * B = ", torch.mm(A, B))
print("A @ B = ", A @ B)

A =  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
B =  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
A * B =  tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])
A @ B =  tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [30]:
# 2.3.10 范数
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))  # 5.0 默认 L2 范数
print(torch.norm(u, 1))  # 7.0 L1 范数
print(torch.norm(u, 2))  # 5.0 L2 范数
print(torch.norm(u, 3))  # 5.385164807134504 L3 范数

tensor(5.)
tensor(7.)
tensor(5.)
tensor(4.4979)
