In [1]:
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'  # 解决matplotlib报错的问题

In [2]:
# 5.4.1 不带参数的层
import torch
import torch.nn.functional as F
from torch import nn

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super(CenteredLayer, self).__init__()

    def forward(self, x):
        return x - x.mean()

In [4]:
layer = CenteredLayer()
layer(torch.FloatTensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]))

tensor([[-2.5000, -1.5000, -0.5000],
        [ 0.5000,  1.5000,  2.5000]])

In [5]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer()
)

y = net(torch.rand(4, 8))
y.mean()

tensor(-2.3283e-09, grad_fn=<MeanBackward0>)

In [6]:
# 5.4.2 带参数的层

class MyLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super(MyLayer, self).__init__()
        self.weight = nn.Parameter(torch.randn(in_features, out_features))
        self.bias = nn.Parameter(torch.randn(out_features))

    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLayer(5, 3)
linear.weight

Parameter containing:
tensor([[-0.7741, -0.6900, -1.9964],
        [ 2.2275,  0.8036, -1.1823],
        [-1.1161,  0.1822, -0.1972],
        [ 0.2185, -0.0029, -0.4530],
        [ 1.1977,  0.7610, -0.5518]], requires_grad=True)

In [8]:
linear(torch.rand(2,5))

tensor([[0.3751, 0.2528, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [9]:
net = nn.Sequential(MyLayer(64,8),MyLayer(8,1))
net(torch.randn(2,64))

tensor([[1.1457],
        [0.0000]])